f-lab-edu/in-bob-we-trust

order-server/build.gradle, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/model/vo/DeliveryStatus.java, order-server/src/main/java/com/inbobwetrust/repository/DeliveryRepository.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java
=> #18 주문상태확인 API

order-server/build.gradle, order-server/src/main/java/com/inbobwetrust/model/vo/Delivery.java, order-server/src/main/java/com/inbobwetrust/model/vo/Order.java, order-server/src/main/java/com/inbobwetrust/producer/DeliveryProducer.java, order-server/src/main/java/com/inbobwetrust/producer/DeliveryProducerImpl.java, order-server/src/main/java/com/inbobwetrust/producer/OrderProducer.java, order-server/src/main/java/com/inbobwetrust/producer/OrderProducerImpl.java, order-server/src/main/java/com/inbobwetrust/repository/ShopsRepository.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/main/java/com/inbobwetrust/service/EndpointService.java, order-server/src/test/java/com/inbobwetrust/producer/DeliveryProducerImplTest.java, order-server/src/test/java/com/inbobwetrust/producer/OrderProducerImplTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java
=> #23 외부로 요청 전송 기능

.github/workflows/Gradle-Build-Test.yml, .github/workflows/google-java-format.yml, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/controller/OrderController.java, order-server/src/main/java/com/inbobwetrust/controller/RiderController.java, order-server/src/main/java/com/inbobwetrust/model/vo/Delivery.java, order-server/src/main/java/com/inbobwetrust/model/vo/Rider.java, order-server/src/main/java/com/inbobwetrust/producer/DeliveryProducerImpl.java, order-server/src/main/java/com/inbobwetrust/producer/OrderProducerImpl.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/main/java/com/inbobwetrust/service/EndpointService.java, order-server/src/main/java/com/inbobwetrust/service/OrderService.java, order-server/src/main/java/com/inbobwetrust/service/RiderService.java, order-server/src/test/java/com/inbobwetrust/ApplicationTest.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/controller/OrderControllerTest.java, order-server/src/test/java/com/inbobwetrust/controller/RiderControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/vo/OrderTest.java, order-server/src/test/java/com/inbobwetrust/producer/DeliveryProducerImplTest.java, order-server/src/test/java/com/inbobwetrust/producer/OrderProducerImplTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java, order-server/src/test/java/com/inbobwetrust/service/OrderServiceTest.java, order-server/src/test/java/com/inbobwetrust/service/RiderServiceTest.java
=> Github Actions을 적용해 push, PR시 Gradle Build Test 자동화

order-server/src/main/java/com/inbobwetrust/model/entity/Agency.java, order-server/src/main/java/com/inbobwetrust/model/entity/Delivery.java, order-server/src/main/java/com/inbobwetrust/model/entity/Order.java, order-server/src/main/java/com/inbobwetrust/model/entity/OrderStatus.java, order-server/src/main/java/com/inbobwetrust/model/entity/Rider.java, order-server/src/main/java/com/inbobwetrust/model/entity/Shop.java, order-server/src/main/resources/application.yml
=> Fix : 오타수정 entitiy > entity

order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/RiderControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/RiderController.java, order-server/src/main/java/com/inbobwetrust/exceptions/EmptyResultSetException.java, order-server/src/main/java/com/inbobwetrust/exceptions/EmptyResultSetSqlException.java, order-server/src/main/java/com/inbobwetrust/exceptions/NoAffectedRowsSqlException.java, order-server/src/main/java/com/inbobwetrust/model/entity/RiderLocation.java, order-server/src/main/java/com/inbobwetrust/service/RiderLocationService.java, order-server/src/main/java/com/inbobwetrust/service/RiderService.java, order-server/src/main/resources/mybatis/mapper/DeliveryRepository.xml, order-server/src/main/resources/mybatis/mapper/OrderRepository.xml, order-server/src/main/resources/mybatis/mapper/RiderLocationRepository.xml, order-server/src/test/java/com/inbobwetrust/controller/RiderControllerTest.java, order-server/src/test/java/com/inbobwetrust/repository/RiderLocationRepositoryTest.java, order-server/src/test/java/com/inbobwetrust/service/RiderServiceTest.java
- Issue #53 와 Issue #54 작업 과정에서 발생한 테스트 fail 케이스들 정리
=> #38 수정사항 과정에서 발생한 테스트 실패 fix

order-server/src/main/java/com/inbobwetrust/model/entity/OrderStatus.java, order-server/src/test/java/com/inbobwetrust/model/entity/OrderStatusTest.java
=> #62 주문상태 기능 추가

order-server/src/main/java/com/inbobwetrust/model/entity/Order.java, order-server/src/main/java/com/inbobwetrust/model/entity/OrderStatus.java, order-server/src/main/java/com/inbobwetrust/repository/OrderRepository.java, order-server/src/main/java/com/inbobwetrust/service/OrderService.java, order-server/src/main/resources/data-test-h2.sql, order-server/src/main/resources/mybatis/mapper/OrderRepository.xml, order-server/src/main/resources/schema.sql, order-server/src/test/java/com/inbobwetrust/repository/OrderRepositoryTest.java, order-server/src/test/java/com/inbobwetrust/service/OrderServiceTest.java
=> #60 mapper 작성 (주문)

order-server/src/main/java/com/inbobwetrust/repository/DeliveryRepository.java, order-server/src/main/resources/mybatis/mapper/DeliveryRepository.xml, order-server/src/test/java/com/inbobwetrust/repository/DeliveryRepositoryTest.java
=> #65 Fix : 스키마 변경으로인한 테스트 실패

order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/RiderControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/RiderController.java, order-server/src/main/java/com/inbobwetrust/model/dto/RiderLocationDto.java, order-server/src/main/java/com/inbobwetrust/model/entity/RiderLocation.java, order-server/src/main/java/com/inbobwetrust/model/mapper/RiderMapper.java, order-server/src/test/java/com/inbobwetrust/controller/RiderControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/RiderLocationDtoTest.java, order-server/src/test/java/com/inbobwetrust/model/mapper/RiderMapperTest.java
- RiderLocationDTO 추가
- RiderController에 DTO 로 수정
- part of #30
=> #30 라이더 dto 적용

order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/DeliveryControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/model/dto/DeliveryCreateDto.java, order-server/src/main/java/com/inbobwetrust/model/entity/Delivery.java, order-server/src/main/java/com/inbobwetrust/model/mapper/DeliveryMapper.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliveryCreateDtoTest.java, order-server/src/test/java/com/inbobwetrust/model/mapper/DeliverMapperTest.java
- part of 데이터 객체 정의 #30
- `DeliveryCreateDto` 추가
- `DeliveryMapper` 추가
- ` RiderController`의 리턴타입 로 수정
=> #30 배달 dto 적용 주문접수

order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/DeliveryControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/model/dto/DeliverySetRiderDto.java, order-server/src/main/java/com/inbobwetrust/model/mapper/DeliveryMapper.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliverySetRiderDtoTest.java, order-server/src/test/java/com/inbobwetrust/model/mapper/DeliverMapperTest.java
- part of Issue #30
- `DeliverySetRiderDto` 추가
- `DeliveryMapper` 매핑 메소드 추가
- ` DeliveryController.setRider` 리턴타입 수정
=> #30 배달dto 적용 라이더배정

order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/DeliveryControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/model/dto/DeliveryStatusDto.java, order-server/src/main/java/com/inbobwetrust/model/mapper/DeliveryMapper.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliveryStatusDtoTest.java, order-server/src/test/java/com/inbobwetrust/model/mapper/DeliverMapperTest.java
- part of Issue #30
- `DeliveryStatusDto` 수정
- `DeliveryMapper` 매핑 메소드 수정
- ` DeliveryController.setStatusToPickup` 리턴타입 수정
=> #30 배달상태 업데이트 픽업완료

order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/DeliveryControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/model/dto/DeliveryGetStatusDto.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliveryGetStatusDtoTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliveryStatusDtoTest.java
- part of Issue #30
- ` DeliveryController.setStatusToPickup` 리턴타입 수정
- 테스트코드 수정
- `*ControllerSwaggerDoc` 인터페이스 수정
=> #30 배달상태확인 and 배달완료

order-server/src/main/java/com/inbobwetrust/aop/ExceptionHandlerControllerAdvice.java, order-server/src/main/java/com/inbobwetrust/model/dto/DeliveryCreateDto.java, order-server/src/main/java/com/inbobwetrust/model/entity/Delivery.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliveryCreateDtoTest.java, order-server/src/test/java/com/inbobwetrust/model/entity/DeliveryTest.java, order-server/src/test/java/com/inbobwetrust/model/mapper/DeliverMapperTest.java, order-server/src/test/java/com/inbobwetrust/producer/DeliveryProducerImplTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java, order-server/src/test/java/com/inbobwetrust/util/vo/DeliveryInstanceGenerator.java
=> #31 신규주문접수 validation

order-server/src/main/java/com/inbobwetrust/aop/ExceptionHandlerControllerAdvice.java, order-server/src/main/java/com/inbobwetrust/model/entity/Delivery.java, order-server/src/main/java/com/inbobwetrust/model/entity/Rider.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/main/resources/schema.sql, order-server/src/test/java/com/inbobwetrust/model/entity/DeliveryTest.java, order-server/src/test/java/com/inbobwetrust/model/entity/RiderTest.java, order-server/src/test/java/com/inbobwetrust/repository/DeliveryRepositoryTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java
- part of Issue #31
- `라이더배정` 기능 동작과정에서 필요한 Validation 들을 구현
=> #31 라이더배정 validation

order-server/src/main/java/com/inbobwetrust/model/dto/DeliveryStatusDto.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/model/dto/DeliveryStatusDtoTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java
- part of Issue #31
- 배달상태 업데이트 기능의 Validation을 위한 필드값 추가
- `DeliveryStatusDto`수정
=> #31 배달상태 dto 필드 추가

order-server/build.gradle
=> #83 프로젝트 셋업

.github/workflows/google-java-format.yml, order-server/build.gradle, order-server/src/integrationTest/java/com/inbobwetrust/DeliveryControllerIntgrationTest.java, order-server/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest.java, order-server/src/main/java/com/inbobwetrust/domain/Delivery.java, order-server/src/main/java/com/inbobwetrust/exception/ExceptionHandlerAdvice.java, order-server/src/main/java/com/inbobwetrust/exception/RelayClientException.java, order-server/src/main/java/com/inbobwetrust/exception/RelayServerException.java, order-server/src/main/java/com/inbobwetrust/publisher/DeliveryPublisher.java, order-server/src/main/java/com/inbobwetrust/publisher/DeliveryPublisherImpl.java, order-server/src/main/java/com/inbobwetrust/publisher/PublisherConfig.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, order-server/src/main/resources/application-test.yml, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java
- Issue #87 의 **Sub-Issue**입니다.
- PR #90 의 "next"입니다.
- 신규주문접수 요청을 받아서 DB에 저장한 이후 해당 정보를 가지고 사장님에게 접수요청을 전송하는 유저플로우입니다.
=> #87 신규주문접수 기능 - 사장님 주문접수요청

order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java
=> #95 배달대행사 라이더배정 기능

order-server/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest.java, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/domain/Delivery.java, order-server/src/main/java/com/inbobwetrust/domain/DeliveryStatus.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/domain/DeliveryStatusTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java
- Issue #97 의 **주문픽업 업데이트** 기능 구현
- Issue #97 의 **배달완료 업데이트** 기능 구현
=> #98 라이더 배달상태 업데이트 기능 (주문픽업, 배달완료)

order-server/src/integrationTest/java/com/inbobwetrust/repository/MovieInfoRepositoryIntegrationTest.java, order-server/src/main/java/com/inbobwetrust/config/swaggerdoc/DeliveryControllerSwaggerDoc.java, order-server/src/main/java/com/inbobwetrust/controller/DeliveryController.java, order-server/src/main/java/com/inbobwetrust/repository/DeliveryRepository.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryService.java, order-server/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, order-server/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, order-server/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java
=> #98 배달정보조회 기능 추가

delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest.java, delivery-info-service/src/main/java/com/inbobwetrust/publisher/DeliveryPublisherImpl.java, delivery-info-service/src/main/resources/application-test.yml, delivery-info-service/src/main/resources/application.yml, delivery-relay-service/src/main/java/com/inbobwetrust/relay/DeliveryRelayRepository.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/RelayController.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/RelayRepository.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/Delivery.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/DeliveryStatus.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/ReceiverType.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/RelayRequest.java, delivery-relay-service/src/main/resources/application.yml
=> #112 delivery relay service 서버 구현

delivery-relay-service/src/main/java/com/inbobwetrust/relay/RelayController.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/Delivery.java, delivery-relay-service/src/test/java/com/inbobwetrust/relay/RelayControllerTest.java
- Issue #118 의 부분
- 기존 RelayController 의 리턴 타입을 RelayRequest에서 Delivery 로 변경
- RelayRequest는 사실상 delivery-relay-service 모듈만의 관심사이기 때문
=> #118 (part of) RelayController가 Delivery 리턴하게 변경

delivery-info-service/build.gradle, delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest.java, delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/TestParameterGenerator.java, delivery-info-service/src/integrationTest/java/com/inbobwetrust/repository/DeliveryRepositoryIntegrationTest.java, delivery-info-service/src/main/java/com/inbobwetrust/controller/DeliveryController.java, delivery-info-service/src/main/java/com/inbobwetrust/domain/Delivery.java, delivery-info-service/src/main/java/com/inbobwetrust/exception/ExceptionHandlerAdvice.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, delivery-info-service/src/test/java/com/inbobwetrust/domain/DeliveryStatusTest.java, delivery-info-service/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java, delivery-relay-service/build.gradle, delivery-relay-service/src/main/java/com/inbobwetrust/relay/ExceptionHandlerAdvice.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/RelayController.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/Delivery.java, delivery-relay-service/src/test/java/com/inbobwetrust/relay/RelayControllerTest.java
- Issue #123 의 준비단계입니다.
- Issue #123을 바로 적용할 수 없기때문에 임시로 프로젝트에서 한번 수동적용해줍니다.
=> #123 (part) Intellij의 Optimize Imports 수동적용

delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest.java, delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/TestParameterGenerator.java, delivery-info-service/src/integrationTest/java/com/inbobwetrust/database/DatabaseConnectionFailoverTest.java, delivery-info-service/src/main/java/com/inbobwetrust/controller/DeliveryController.java, delivery-info-service/src/main/java/com/inbobwetrust/domain/Delivery.java, delivery-info-service/src/main/java/com/inbobwetrust/exception/ExceptionHandlerAdvice.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryService.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, delivery-info-service/src/test/java/com/inbobwetrust/domain/DeliveryStatusTest.java, delivery-info-service/src/test/java/com/inbobwetrust/repository/DeliveryRepositoryIntegrationTest.java, delivery-info-service/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/ExceptionHandlerAdvice.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/RelayController.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/domain/Delivery.java, delivery-relay-service/src/test/java/com/inbobwetrust/relay/RelayControllerTest.java
- Issue #127 의 sub-PR
- Intellij 의 import optimize 실행
=> #127 리팩토링 시즌 1 : Intellij Optimize Imports

.github/workflows/delivery-info-service.gradle-generate-jacoco-test-coverage.yml, .github/workflows/delivery-info-service.gradle-integration-test.yml, .github/workflows/delivery-relay-service.gradle-generate-jacoco-test-coverage.yml, delivery-info-service/build.gradle, delivery-info-service/src/integrationTest/java/com/inbobwetrust/database/DatabaseConnectionFailoverTest.java, delivery-relay-service/build.gradle
=> #59 Jacoco 테스트 커버리지 관리

.github/workflows/build-delivery-info-service.yml, .github/workflows/build-delivery-relay-service.yml
- PR #134 의 버그를 해결합니다.
- actions의 `github secrets` 변수명을 잘못 입력한 것을 해결합니다. `DOCKER_HUB_PASSWORD >> DOCKERHUB_USERNAME `
- 테스트를 PR에서 완료했다 하더라도 이미지 푸시하기전 다시 한번 테스트를 실행합니다.
=> #130 Fix : 프로덕선 빌드 워크플로우 설정정보 수정

.github/workflows/build-delivery-info-service.yml, .github/workflows/build-delivery-relay-service.yml
- PR #130 프로덕션 빌드 Docker image 빌드 워크플로우 추가 의 버그를 해결합니다.
=> #130 Fix : 프로덕선 빌드 워크플로우 버그 수정 #136

.github/workflows/build-delivery-info-service.yml, .github/workflows/build-delivery-relay-service.yml, delivery-info-service/src/test/java/com/inbobwetrust/repository/DeliveryRepositoryIntegrationTest.java, delivery-relay-service/src/test/java/com/inbobwetrust/relay/RelayControllerTest.java
- resolves #130
- resolves bug from #130
=> #130 Fix : Build Worfklow 버그

k6-test/docker-compose-actions.yml, k6-test/process_cpu_usage.js, k6-test/prometheus.yml, k6-test/simple-delivery-get.js, script/loadtest-local.sh
- K6와 Prometheus의 Integration 을 통해서 K6의 테스트 결과를 Prometheus 에 push 방식으로 전송합니다.
- 이 기능은 K6 공식 홈페이지에서 소개되어있습니다. https://k6.io/blog/k6-loves-prometheus/
- `xk6` (k6에 기능을 플러그인 하기위한 binary 익스텐션) 를  받아서 prometheus 의 `remote-write `기능을 활성화합니다.
=> #142 k6 로드테스트 결과 prometheus 에서 취합하기

delivery-info-service/build.gradle, delivery-info-service/lombok.config, delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest.java, delivery-info-service/src/main/java/com/inbobwetrust/controller/DeliveryController.java, delivery-info-service/src/main/java/com/inbobwetrust/exception/ExceptionHandlerAdvice.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/ApplicationTest.java, delivery-info-service/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, delivery-info-service/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java, delivery-info-service/src/test/java/com/inbobwetrust/service/DeliveryServiceTest.java, delivery-relay-service/build.gradle, delivery-relay-service/src/test/java/com/inbobwetrust/DeliveryRelayServiceApplicationTest.java
- part of Issue #149
- 목표를 100%으로 맞춰두었으나 계속 실패하기때문에 잠시 60으로 맞춰둡니다.
- **delivery-info-service** 모듈 테스트 커버리지 증가
- Instruction Coverage >> 72% 
-  Branches Coverage >> 95%
- 테스트 제외 항목
- `Lombok.generated` 항목들은 제외됩니다.
- `Application.class`는 제외됩니다.
=> #149 [delivery-info-service] 테스트 커버리지 up to Instruction 72% / Branches 95

delivery-info-service/build.gradle, delivery-info-service/src/main/java/com/inbobwetrust/domain/DeliveryStatus.java, delivery-info-service/src/main/java/com/inbobwetrust/exception/ExceptionHandlerAdvice.java, delivery-info-service/src/main/java/com/inbobwetrust/publisher/DeliveryPublisherImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/domain/DeliveryStatusTest.java, delivery-info-service/src/test/java/com/inbobwetrust/domain/DeliveryTest.java, delivery-info-service/src/test/java/com/inbobwetrust/exception/ExceptionHandlerAdviceTest.java, delivery-info-service/src/test/java/com/inbobwetrust/publisher/DeliveryPublisherImplTest.java, delivery-relay-service/build.gradle
- part of Issue #149
- 목표로 세운 전체 `Instruction 100%` 와  `Branche 100%` 를 반영했습니다.
- **delivery-info-service** 모듈 테스트 커버리지 증가
- 테스트 제외 항목
- `Lombok.generated` 항목들은 제외됩니다.
- `Application.class`는 제외됩니다.
=> #149 전체 테스트 커버리지 100%

.github/workflows/rider-location-service.yml, rider-location-service/build.gradle, rider-location-service/lombok.config, rider-location-service/src/integrationTest/java/com/inbobwetrust/ApplicationTest.java, rider-location-service/src/main/java/com/inbobwetrust/RiderLocationApplication.java, rider-location-service/src/main/java/com/inbobwetrust/config/RiderLocationRedisConfiguration.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocation.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationController.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationRepository.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationService.java, rider-location-service/src/test/java/com/inbobwetrust/ApplicationTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/RiderLocationControllerTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/RiderLocationServiceTest.java, settings.gradle
=> #129 라이더 위치 추적 기능 : rider-location-service Init

delivery-info-service/build.gradle, rider-location-service/build.gradle, rider-location-service/src/integrationTest/java/com/inbobwetrust/domain/RiderLocationWriteTest.java, rider-location-service/src/main/java/com/inbobwetrust/RiderLocationApplication.java, rider-location-service/src/main/java/com/inbobwetrust/config/JacocoNotGenerated.java, rider-location-service/src/main/java/com/inbobwetrust/config/RiderLocationRedisConfiguration.java, rider-location-service/src/main/java/com/inbobwetrust/domain/DeliveryRepository.java, rider-location-service/src/main/java/com/inbobwetrust/domain/DeliveryRepositoryImpl.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocation.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationController.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationRepository.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationRepositoryImpl.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationService.java, rider-location-service/src/main/resources/application.yml, rider-location-service/src/test/java/com/inbobwetrust/domain/DeliveryRepositoryImplTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/RiderLocationControllerTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/RiderLocationServiceTest.java
=> #129 라이더위치 write 기능 추가

delivery-info-service/build.gradle, delivery-info-service/src/integrationTest/java/com/inbobwetrust/controller/DeliveryControllerIntgrationTest2.java, delivery-info-service/src/main/java/com/inbobwetrust/controller/DeliveryController.java, delivery-info-service/src/main/java/com/inbobwetrust/domain/Delivery.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryService.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/controller/DeliveryControllerTest.java, delivery-info-service/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java, k6-test/simple-delivery-get.js
=> #129 delivery info service 픽업완료 api 추가

delivery-info-service/src/main/resources/application-production.yml, delivery-info-service/src/main/resources/application.yml
- part of issue #158 
- AWS ECS 연동을 위한 준비 작업입니다.
- 컨테이너 실행시 필요한 과도한 작업들을 기본으로 설정해줍니다.
=> #158 [delivery-info-service] default 프로필설정

.github/workflows/delivery-info-service.yml
- part of issue #158 
- delivery-info-service 의 로드테스트 워크플로우 삭제합니다.
- 테스트 프로세스의 흐름이 확정될때까지 삭제합니다.
=> #158 [delivery-info-service] 워크플로우 job "load_test" 삭제

.github/workflows/delivery-info-service.yml, .github/workflows/delivery-relay-service.yml, .github/workflows/rider-location-service.yml
- part of issue #158 
- main 브랜치에서만 이미지 빌드합니다.
=> #158 main 브랜치 push 이벤트 build_image 워크플로우

delivery-info-service/src/main/java/com/inbobwetrust/controller/HealthCheckController.java, delivery-info-service/src/main/resources/application.yml, delivery-info-service/src/test/java/com/inbobwetrust/controller/HealthCheckControllerTest.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/HealthCheckController.java, delivery-relay-service/src/main/resources/application.yml, delivery-relay-service/src/test/java/com/inbobwetrust/relay/HealthCheckControllerTest.java, rider-location-service/src/main/java/com/inbobwetrust/domain/HealthCheckController.java, rider-location-service/src/main/resources/application.yml, rider-location-service/src/test/java/com/inbobwetrust/domain/HealthCheckControllerTest.java
- part of issue #158 
- 클라우드에서 유용향 PING 을 추가합니다.
=> #158 ping 엔드포인트 추가하기

aws/user-data/prometheus.yml, aws/user-data/run-container-prometheus.sh, aws/user-data/run-container-zipkin.sh, delivery-info-service/build.gradle, delivery-info-service/src/main/resources/application-production.yml, delivery-info-service/src/main/resources/application.yml, delivery-info-service/src/main/resources/bootstrap.yml, delivery-relay-service/build.gradle, delivery-relay-service/src/main/resources/application-production.yml, delivery-relay-service/src/main/resources/application.yml, delivery-relay-service/src/main/resources/bootstrap.yml
- part of #172
- Issue #172 에서 상세 내용확인가능합니다.
=>  #172 Observability 서비스 적용

.github/workflows/delivery-info-service.yml, .github/workflows/delivery-relay-service.yml, delivery-info-service/build.gradle, delivery-info-service/src/main/java/com/inbobwetrust/publisher/DeliveryPublisherImpl.java, delivery-info-service/src/main/java/com/inbobwetrust/service/DeliveryServiceImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/service/DeliveryServiceImplTest.java, delivery-relay-service/src/main/java/com/inbobwetrust/relay/RelayController.java
- part of #172 
- 이슈 #172 의 6번항목인 블로그 과정에서 발생한 성능 개선 부분입니다.
=> #172 minor한 성능개선

readme.md
- part of #183 
- 2022-02-01 까지 진행한 프로젝트 관련 기술 블로그를 메인 readme 에  공유합니다.
=> #183 Doc : 프로젝트 Doc & 기술 블로그 동기화 as of 2022-02-01

.github/workflows/delivery-info-service.yml, .github/workflows/delivery-relay-service.yml, readme.md
- part of #183 
- 멘토링 기간 3개월 이후 프로젝트 점검 시간이 필요하다 생각이 되었습니다.
- `readme.md` 앞으로 프로젝트 진행을 위해 고려해볼만한 질문들을 정리했습니다.
- `AWS 관련 워크플로우`성능 테스트 관련 진행중인 부분이 없어서 AWS EC2 서버 잠시 내렸습니다.
=> #183 Chore : EC2 관련 CI 임시종료 & 프로젝트 목표 추가

delivery-relay-service/build.gradle, readme.md, rider-location-service/build.gradle
- part of #183 
- Delivery-Info-Service에만 적용되어있던 Swagger-Ui API 도큐먼트 툴을  적용합니다. 
- Delivery-Relay-Service
- Rider-Location-Service
=> #183 swagger UI 전체적용

.github/workflows/customer-chat-service.yml, customer-chat-service/build.gradle, customer-chat-service/lombok.config, customer-chat-service/src/main/java/com/inbobwetrust/Application.java, customer-chat-service/src/main/resources/application-test.yml, customer-chat-service/src/main/resources/application.yml, customer-chat-service/src/test/java/com/inbobwetrust/ApplicationTest.java, readme.md, settings.gradle
- Issue #190 를 위한 준비작업입니ㅏㄷ.
- customer-chat-service 모듈을 추가합니다.
=> #190 채팅기능 구현을 위한 customer-chat-service 모듈 초기화

rider-location-service/src/integrationTest/java/com/inbobwetrust/domain/RiderLocationWriteTest.java, rider-location-service/src/main/java/com/inbobwetrust/controller/HealthCheckController.java, rider-location-service/src/main/java/com/inbobwetrust/controller/RiderLocationController.java, rider-location-service/src/main/java/com/inbobwetrust/domain/RiderLocationService.java, rider-location-service/src/main/java/com/inbobwetrust/repository/DeliveryRepository.java, rider-location-service/src/main/java/com/inbobwetrust/repository/DeliveryRepositoryImpl.java, rider-location-service/src/main/java/com/inbobwetrust/repository/RiderLocationRepository.java, rider-location-service/src/main/java/com/inbobwetrust/repository/RiderLocationRepositoryImpl.java, rider-location-service/src/main/java/com/inbobwetrust/service/RiderLocationService.java, rider-location-service/src/test/java/com/inbobwetrust/domain/DeliveryRepositoryImplTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/HealthCheckControllerTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/RiderLocationControllerTest.java, rider-location-service/src/test/java/com/inbobwetrust/domain/RiderLocationServiceTest.java
- part of #193
- 프로젝트 전반 모듈 구조를 통일시킵니다.
=> #193 rider location service 모듈 구조 변경

delivery-relay-service/src/main/java/com/inbobwetrust/controller/HealthCheckController.java, delivery-relay-service/src/main/java/com/inbobwetrust/controller/RelayController.java, delivery-relay-service/src/main/java/com/inbobwetrust/domain/Delivery.java, delivery-relay-service/src/main/java/com/inbobwetrust/domain/DeliveryStatus.java, delivery-relay-service/src/main/java/com/inbobwetrust/domain/ReceiverType.java, delivery-relay-service/src/main/java/com/inbobwetrust/domain/RelayRequest.java, delivery-relay-service/src/main/java/com/inbobwetrust/exception/ExceptionHandlerAdvice.java, delivery-relay-service/src/main/java/com/inbobwetrust/repository/RelayRepository.java, delivery-relay-service/src/test/java/com/inbobwetrust/relay/HealthCheckControllerTest.java, delivery-relay-service/src/test/java/com/inbobwetrust/relay/RelayControllerTest.java
- part of #193
- 프로젝트 전반 모듈 구조를 통일시킵니다.
- `delivery-relay-service` 그레이들 모듈의 구조를 `controller-service-repository`의 웹 레이어로 변경
=> #193 delivery relay service 모듈 구조 변경

.github/workflows/google-java-format.yml, delivery-info-service/src/main/java/com/inbobwetrust/publisher/DeliveryMessagePublisherImpl.java, delivery-info-service/src/test/java/com/inbobwetrust/publisher/DeliveryMessagePublisherImplTest.java
- part of issue #198 
- 배달의민족 주문서버에서 `POST /delivery`로 전송받는 신규주문에 대한 `사장님에게 주문접수를 요청` 메시지를 전송하는 구현
- 사장님으로부터 `PUT /delivery`로 전송받는 접수된 주문건 대한 `배달대행사에 라이더배정 요청` 메시지를 전송하는 로직구현
=> #198 주문 발생 이벤트 publisher 작성

delivery-info-service/src/main/java/com/inbobwetrust/config/Jack2JsonConfiguration.java
- 현재 RabbitMQ 클라이언트에서 사용되는 MessageConverter 의 Bean 타입을 더 Abstract한 레벨로 적용
=> #Refactor 메시지큐에 사용되는 MessageConverter 빈 타입 추상화
